### ISSUE TITLE
error when running test command

### ISSUE THREAD

**Issue by Abdullah-Ghani** [iceberg-project/Penguins#16]
```
$ iceberg_penguins.detect
Traceback (most recent call last):
  File "/home/aag193/Penguins/iceberg_penguins/bin/iceberg_penguins.detect", line 15, in <module>
    from iceberg_penguins.search.models import create_model
  File "/home/aag193/Penguins/iceberg_penguins/lib/python3.5/site-packages/iceberg_penguins/search/models/__init__.py", line 2, in <module>
    from .base_model import BaseModel
  File "/home/aag193/Penguins/iceberg_penguins/lib/python3.5/site-packages/iceberg_penguins/search/models/base_model.py", line 10
    import ..util.util as util
           ^
SyntaxError: invalid syntax
```

**Comment by AymenFJA** [comment]
@Abdullah-Ghani this problem is solved now with the latest release. Please install the package using this link [iceberg-penguins.search](https://pypi.org/project/iceberg-penguins.search/)
